### ISSUE TITLE
[BUG] Yelp API Validation Error

### ISSUE THREAD

**Issue by anmagnot** [microsoft/PowerPlatformConnectors#1104]
### Type of Connector

Independent Publisher Connector

### Name of Connector

Yelp (Independent Publisher)

### Describe the bug

Added the Yelp (Independent Publisher) connector to my Dataverse environment via connections and connected with my Yelp Developer API Key. Getting the following Validation errors when attempting to run any actions in either Power Automate or Power Apps:

**Power Automate error:** 
{
  "error": {
    "code": "VALIDATION_ERROR",
    "description": "'_my yelp developer api key_' does not match '^(?i)Bearer [A-Za-z0-9\\\\-\\\\_]{128}$'",
    "field": "Authorization",
    "instance": "_my yelp developer api key_"
  }
}

### Is this a security bug?

No, this is not a security bug

### What is the severity of this bug?

Severity 3 - Minor issue

### To Reproduce

1. https://make.preview.powerapps.com/
2. Under Dataverse -> Connectors -> +New Connection
3. Search and Select 'Yelp (Independent Publisher) (preview)'
4. Input Yelp API from Yelp: https://www.yelp.com/developers/v3/manage_app?app_created=True
5. Back in Power Apps, under Flows -> Create New Instant Cloud Flow
6. In the Power Automate Flow editor add the Yelp Business Search action utilizing the connection from step 4
7. Manually Test the flow and input an actual YelpId for a business
8. Flow fails with the Validation error above.

### Expected behavior

The flow should execute with by returning the proper Business data from the Yelp API

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build)
CLI version (paconn --version)
OS version
Shell Type (e.g. bash, cmd.exe, Bash on Windows)

### Additional context

N/A

**Comment by ahmadn82** [comment]
Hi Andrew,

Thank you for reporting this issue!
I have anticipated that this might happen, so I have pushed some updates to the connector (v 1.1). However, the updates are not pushed into production yet. 
So in order to overcome this issue please provide you API key as follows:
"Bearer YOUR_API_KEY"

This should solve the problem for the time being, however once the updates are pushed into production, you need to update your connections with the API_KEY only without "Bearer".

Thanks again

Ahmad Najjar

**Comment by anmagnot** [comment]
Ahmad - Thanks! That fix worked. I'm now able to execute against the Yelp API form both Power Automate and Power Apps.
