### ISSUE TITLE
[BUG] ShipStationIP Basic Authentication

### ISSUE THREAD

**Issue by SmolSoftBoi** [microsoft/PowerPlatformConnectors#1763]
### Type of Connector

Independent Publisher Connector

### Name of Connector

ShipStationIP

### Describe the bug

The API definition has basic authentication, but this is not asked for?

### Is this a security bug?

No, this is not a security bug

### What is the severity of this bug?

Severity 1 - Connector is broken or there's a very serious issue

### To Reproduce

Add a connection, no basic authentication is asked for.

### Expected behavior

Basic authentication should be asked for.

### Environment summary

Install Method: Power Automate

### Additional context

…

**Comment by natalie-pienkowska** [comment]
Thank you @SmolSoftBoi for submitting this issue! @Amjed-Ayoub will take a look at this issue with his team and then get back to you with an update.

**Comment by Amjed-Ayoub** [comment]
Hi @SmolSoftBoi, Thank you so much for reaching out. Please allow me some time to work with our engineers on this. Please expect to hear back from me soon.
Thank you so much again for your patience and understanding.

**Comment by v-EgorKozhadei** [comment]
Hi @SmolSoftBoi,

Thank you for submitting an issue!

I was able to reproduce the bug. I analyzed connector files and found a few things.

For creating a connection with [Basic Authentication](https://docs.microsoft.com/en-us/connectors/custom-connectors/connection-parameters#basic-authentication) we need a username and a password. In the [apiProperties file](https://docs.microsoft.com/en-us/connectors/custom-connectors/paconn-cli#api-properties-file) the [connectionParameters property is not defined](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/independent-publisher-connectors/ShipStationIP/apiProperties.json#L3), that's why it's not asking for authentication. Also I haven't found the security property in apiDefinition.swagger.json file. It's necessary to define the connectionParameters in apiProperties.json and securityDefinitions and security properties in apiDefinition.swagger.json.

I can provide an example from one of the existing IP connectors called UdemyIP. Please take a look at [securityDefinitions](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/independent-publisher-connectors/Udemy/apiDefinition.swagger.json#L803) and [security](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/independent-publisher-connectors/Udemy/apiDefinition.swagger.json#L808) properties from apiDefinition.swagger.json file and at [connectionParameters](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/independent-publisher-connectors/Udemy/apiProperties.json#L3) property from apiPropertiesjson file.

Could you please raise a quick PR with a fix in the open-source repository?

Let us know if you have any questions or need help!

**Comment by SmolSoftBoi** [comment]
Fixed in #1813

**Comment by v-EgorKozhadei** [comment]
Hello @SmolSoftBoi,

Closing the issue because it was fixed in the PR mentioned above.

Please let us know by reopening the issue if there are any problems.
