### ISSUE TITLE
Understanding the process in the independent publisher connectors.

### ISSUE THREAD

**Issue by ravikiran-srini** [microsoft/PowerPlatformConnectors#1781]
### Description of Feature or Work Requested

Contradiction in docs.

This link says that both independent publishers and verified publishers can certify get a connector certified
https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-certification#who-is-eligible-to-get-a-connector-certified

This link (answer to Q1) says that you need to own an API or have exclusive rights to certify it, which independent publishers don't have.
https://docs.microsoft.com/en-us/connectors/custom-connectors/faq#certification

Please help clear the misunderstanding.

Also, what's the difference between publishing and certifying? Doesn't all the published custom connectors in the Power Platform have been certified?

### Target Date

This issue is related to understanding the process in the independent publisher connectors.

**Comment by natalie-pienkowska** [comment]
Thanks for your question and for calling out this confusing point. I will have our team address this immediately.

Both verified publishers and independent publishers can get their connector certified (reviewed and approved by Microsoft) and published (released to the Power Platform). 

You need to own the API in order to have it certified and published as a Verified Publisher Connector. You do not need to own the connector in order to have it certified and published as an Independent Publisher connector.

I hope this helps :)

**Comment by v-aangie** [comment]
@ravikiran-srini - Thanks for your feedback. We have updated the docs to fix information about certifying as an independent publisher in https://docs.microsoft.com/en-us/connectors/custom-connectors/faq#certification and the content is now live. Closing this issue.
